version: "3.9"

services:
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: usuario
      DB_PASSWORD: senha
      DB_NAME: MagiCards
      DB_HOST: db
      DB_PORT: 3306

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MagiCards
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
